# Generated by Django 5.2.7 on 2025-10-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrole',
            table='roles_usuarios',
        ),
    ]
