# Generated by Django 5.2.7 on 2025-10-20 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userrole_table'),
        ('authentication', '0003_create_superadmin'),
    ]

    operations = [
    ]
