# Generated by Django 5.2.7 on 2025-10-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'participantes',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'paginas',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events_as_evaluator', to='authentication.customuser')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='ParticipantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_events', to='events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participant_events', to='events.participant')),
            ],
            options={
                'db_table': 'eventos_participantes',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='participants', through='events.ParticipantEvent', to='events.event'),
        ),
        migrations.CreateModel(
            name='ParticipantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='logs')),
                ('message', models.TextField()),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.participant')),
            ],
            options={
                'db_table': 'logs_participantes',
            },
        ),
        migrations.CreateModel(
            name='BlockedHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_hosts', to='events.event')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='blocked_in_events', to='events.website')),
            ],
            options={
                'db_table': 'paginas_bloqueadas',
            },
        ),
        migrations.AddConstraint(
            model_name='participantevent',
            constraint=models.UniqueConstraint(fields=('event', 'participant'), name='unique_participant_per_event'),
        ),
        migrations.AlterUniqueTogether(
            name='blockedhost',
            unique_together={('event', 'website')},
        ),
    ]
