# Generated by Django 5.2.7 on 2025-10-24 00:06

from django.db import migrations


def add_websites(apps, schema_editor):
    Website = apps.get_model("events", "Website")
    hostnames = [
        "chatgpt.com",
        "claude.ai",
        "poe.com",
        "gemini.google.com",
        "copilot.microsoft.com",
        "perplexity.ai",
        "chat.deepseek.com",
        "kimi.com",
        "chat.mistral.ai",
        "pi.ai",
        "you.com",
        "jay.ai",
        "blackbox.ai",
        "textcortex.com",
        "genieai.co",
        "writesonic.com",
        "copy.ai",
        "replika.com",
    ]
    for hostname in hostnames:
        Website.objects.get_or_create(hostname=hostname)


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_websites),
    ]
