# Generated by Django 5.2.7 on 2025-10-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_blockedhost_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='eventos',
        ),
        migrations.AlterModelTable(
            name='participant',
            table='participantes',
        ),
    ]
