# Generated by Django 5.2.7 on 2025-11-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20251023_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_progreso', 'En progreso'), ('completado', 'Completado')], max_length=20),
        ),
    ]
