# Generated by Django 5.1.6 on 2025-02-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participantlog_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantlog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='logs'),
        ),
    ]
