# Generated by Django 5.2.7 on 2025-10-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20251023_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(help_text='Duración en minutos'),
        ),
    ]
