# Generated by Django 5.2.7 on 2025-11-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantlog',
            name='participant',
        ),
        migrations.AddField(
            model_name='participantlog',
            name='participant_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.participantevent'),
        ),
    ]
