# Generated by Django 5.1.6 on 2025-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_participant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
