# Generated by Django 5.2.8 on 2025-11-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_participantevent_is_monitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyUpdateSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('action', models.CharField(default='update_blocked_hosts', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'proxy_update_signals',
                'indexes': [models.Index(fields=['processed', 'created_at'], name='proxy_updat_process_2f7c6f_idx')],
            },
        ),
    ]
