# Generated by Django 5.2.8 on 2025-11-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_add_monitoring_fields_to_participantevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyUpdateSignal',
        ),
    ]
