# Generated by Django 5.2.9 on 2025-12-05 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_delete_proxyupdatesignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Hora UTC en que se registró el log'),
            preserve_default=False,
        ),
    ]
