# Generated by Django 5.2.9 on 2025-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_participantlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantevent',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
