# Generated by Django 5.2.8 on 2025-12-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_participantevent_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantlog',
            name='file',
        ),
        migrations.AddField(
            model_name='participantlog',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
