# Generated by Django 5.2.9 on 2025-12-19 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_participantlog_file_participantlog_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('consent_version', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='events.participant')),
            ],
            options={
                'db_table': 'event_consents',
                'constraints': [models.UniqueConstraint(fields=('participant', 'event'), name='unique_consent_per_participant_event')],
            },
        ),
    ]
