# Generated by Django 5.1.6 on 2025-03-26 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_participant_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_hosts', to='events.event')),
            ],
        ),
    ]
