# Generated by Django 5.2.7 on 2025-10-31 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('participant_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_port', to='events.participantevent')),
            ],
            options={
                'db_table': 'puertos_asignados',
            },
        ),
    ]
