# Generated by Django 5.2.7 on 2025-10-27 01:43

import django.db.models.deletion
import proxy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(default=proxy.models.generate_session_key, max_length=40, unique=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_port', to='events.participant')),
            ],
            options={
                'db_table': 'puertos_asignados',
                'indexes': [models.Index(fields=['port'], name='puertos_asi_port_2b8896_idx'), models.Index(fields=['is_active'], name='puertos_asi_is_acti_1ed93a_idx')],
            },
        ),
    ]
