# Generated by Django 5.2.7 on 2025-10-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedport',
            name='current_session_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedport',
            name='total_duration',
            field=models.IntegerField(default=0, help_text='Duración total en segundos'),
        ),
    ]
