# Generated by Django 5.2.7 on 2025-10-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignedport',
            new_name='puertos_asi_port_2b8896_idx',
            old_name='proxy_assig_port_dcdae6_idx',
        ),
        migrations.RenameIndex(
            model_name='assignedport',
            new_name='puertos_asi_is_acti_1ed93a_idx',
            old_name='proxy_assig_is_acti_aab85f_idx',
        ),
        migrations.AlterModelTable(
            name='assignedport',
            table='puertos_asignados',
        ),
    ]
