# Generated by Django 5.2.8 on 2025-11-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_assignedport_current_session_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedport',
            name='connection_time',
            field=models.IntegerField(blank=True, default=0, help_text='Tiempo total de conexión en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='assignedport',
            name='total_duration',
            field=models.IntegerField(blank=True, default=0, help_text='Duración total en segundos', null=True),
        ),
    ]
