# Generated by Django 5.1.6 on 2025-03-18 16:21

import proxy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_assignedport_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedport',
            name='session_key',
            field=models.CharField(default=proxy.models.generate_session_key, max_length=40, unique=True),
        ),
    ]
