# Generated by Django 5.2.8 on 2025-11-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_assignedport_connection_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedport',
            name='connection_time',
        ),
    ]
