# Generated by Django 5.2.8 on 2025-11-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_remove_connection_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedport',
            name='monitoring_last_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
