# Generated by Django 5.1.6 on 2025-03-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_blockedhost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedHost',
        ),
    ]
