# Generated by Django 5.2.8 on 2025-11-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_assignedport_monitoring_last_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedport',
            name='first_connection_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedport',
            name='monitoring_sessions_count',
            field=models.IntegerField(default=0, help_text='Número de veces que se inició monitoreo'),
        ),
    ]
