# Generated by Django 5.1.6 on 2025-03-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignedport',
            table='proxy_assignedport',
        ),
    ]
