# Generated by Django 5.1.6 on 2025-03-17 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_date_event_end_date_event_start_date'),
        ('proxy', '0002_alter_assignedport_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedport',
            name='session_key',
            field=models.CharField(default='default_session_placeholder', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='assignedport',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_port', to='events.participant'),
        ),
        migrations.AddIndex(
            model_name='assignedport',
            index=models.Index(fields=['port'], name='proxy_assig_port_dcdae6_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedport',
            index=models.Index(fields=['is_active'], name='proxy_assig_is_acti_aab85f_idx'),
        ),
        migrations.AlterModelTable(
            name='assignedport',
            table=None,
        ),
    ]
