# Generated by Django 5.1.6 on 2025-03-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_alter_assignedport_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255, verbose_name='Clave de Evento')),
                ('hostname', models.CharField(max_length=255, verbose_name='Host a bloquear')),
            ],
        ),
    ]
