# Generated by Django 5.2.8 on 2025-11-27 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_proxyupdatesignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisComportamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(max_length=500)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('lipsync_score', models.FloatField(blank=True, null=True)),
                ('lipsync_lag', models.FloatField(blank=True, null=True)),
                ('cantidad_voces_detectadas', models.IntegerField(default=0)),
                ('participant_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_comportamiento', to='events.participantevent')),
            ],
        ),
        migrations.CreateModel(
            name='AnomaliaLipsync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anomalia', models.CharField(max_length=100)),
                ('tiempo_inicio', models.FloatField()),
                ('tiempo_fin', models.FloatField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias_lipsync', to='behavior_analysis.analisiscomportamiento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroGesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gesto', models.CharField(max_length=100)),
                ('tiempo_inicio', models.FloatField()),
                ('tiempo_fin', models.FloatField()),
                ('duracion', models.FloatField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_gestos', to='behavior_analysis.analisiscomportamiento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIluminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anomalia', models.CharField(max_length=100)),
                ('tiempo_inicio', models.FloatField()),
                ('tiempo_fin', models.FloatField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_iluminacion', to='behavior_analysis.analisiscomportamiento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRostro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.IntegerField()),
                ('tiempo_inicio', models.FloatField()),
                ('tiempo_fin', models.FloatField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_rostros', to='behavior_analysis.analisiscomportamiento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_log', models.CharField(max_length=50)),
                ('etiqueta_hablante', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_inicio', models.FloatField()),
                ('tiempo_fin', models.FloatField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_voz', to='behavior_analysis.analisiscomportamiento')),
            ],
        ),
    ]
