# Generated by Django 5.2.8 on 2025-11-27 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analisiscomportamiento',
            table='analisis_comportamiento',
        ),
        migrations.AlterModelTable(
            name='anomalialipsync',
            table='registro_lipsync',
        ),
        migrations.AlterModelTable(
            name='registrogesto',
            table='registro_gesto',
        ),
        migrations.AlterModelTable(
            name='registroiluminacion',
            table='registro_iluminacion',
        ),
        migrations.AlterModelTable(
            name='registrorostro',
            table='registro_rostro',
        ),
        migrations.AlterModelTable(
            name='registrovoz',
            table='registro_voz',
        ),
    ]
