# Generated by Django 5.2.8 on 2025-11-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_analysis', '0002_alter_analisiscomportamiento_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisiscomportamiento',
            name='cantidad_voces_detectadas',
        ),
        migrations.RemoveField(
            model_name='analisiscomportamiento',
            name='lipsync_lag',
        ),
        migrations.RemoveField(
            model_name='analisiscomportamiento',
            name='lipsync_score',
        ),
    ]
