# Generated by Django 5.2.8 on 2025-11-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_analysis', '0003_remove_analisiscomportamiento_cantidad_voces_detectadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisiscomportamiento',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
