# Generated by Django 5.2.8 on 2025-11-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_analysis', '0004_analisiscomportamiento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroiluminacion',
            name='tipo_anomalia',
        ),
    ]
