# Generated by Django 5.2.8 on 2025-11-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_analysis', '0005_remove_registroiluminacion_tipo_anomalia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_inicio', models.FloatField()),
                ('tiempo_fin', models.FloatField()),
                ('duracion', models.FloatField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ausencia', to='behavior_analysis.analisiscomportamiento')),
            ],
            options={
                'db_table': 'registro_ausencia',
            },
        ),
    ]
