# Generated by Django 5.2.9 on 2025-12-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_analysis', '0006_registroausencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisiscomportamiento',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='analisiscomportamiento',
            name='video_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
