# Generated by Django 5.2.8 on 2025-12-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_analysis', '0006_registroausencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analisiscomportamiento',
            old_name='video_path',
            new_name='video_link',
        ),
    ]
