# Generated by Django 5.2.9 on 2025-12-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_analysis', '0007_rename_video_path_analisiscomportamiento_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisiscomportamiento',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
    ]
